"""Instruction fine-tuning script for GPT-2.

Usage:
    uv run python scripts/post_training/sft.py
    uv run python scripts/post_training/sft.py --model gpt2-medium --num-epochs 2 --batch-size 2 --max-length 512 --grad-accumulation-steps 4
"""

import argparse
import json
from functools import partial

import tiktoken
import torch
from torch.utils.data import DataLoader

from legollm.architectures.gpt2 import GPT2, MODEL_CONFIGS, GPT2Variant, load_gpt2_weights
from legollm.generation import SamplingStrategy, generate_and_decode
from legollm.logging import logger, progress_bar
from legollm.post_training.sft import (
    InstructionDataset,
    custom_collate_fn,
    download_and_load_instruction_dataset,
    format_input,
    plot_losses,
    train,
)
from legollm.utils import get_device


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="Instruction fine-tuning for GPT-2")
    parser.add_argument(
        "--model",
        type=str,
        default="gpt2-medium",
        choices=[v.value for v in GPT2Variant],
        help="GPT-2 variant (default: gpt2-medium)",
    )
    parser.add_argument("--num-epochs", type=int, default=5, help="Number of epochs (default: 5)")
    parser.add_argument("--batch-size", type=int, default=4, help="Batch size (default: 4)")
    parser.add_argument(
        "--grad-accumulation-steps",
        type=int,
        default=4,
        help="Gradient accumulation steps (default: 4)",
    )
    parser.add_argument(
        "--max-length",
        type=int,
        default=1024,
        help="Max sequence length for collate truncation (default: 1024)",
    )
    return parser.parse_args()


def main() -> None:
    """Run instruction fine-tuning."""
    args = parse_args()

    # Load data
    file_path = "data/finetuning/instruction_dataset.json"
    url = "https://raw.githubusercontent.com/pytholic/LegoLLM/refs/heads/main/data/finetuning/instruction_dataset.json"
    data = download_and_load_instruction_dataset(file_path, url)

    # Load tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Device
    device = get_device()

    # Customized collate function
    customized_collate_fn = partial(
        custom_collate_fn,
        device=device,
        allowed_max_length=args.max_length,
        pad_token_id=tokenizer.eot_token,
    )

    # Split data into train, test and validation
    train_portion = int(len(data) * 0.85)  # 85% for training
    test_portion = int(len(data) * 0.1)  # 10% for testing

    train_data = data[:train_portion]
    test_data = data[train_portion : train_portion + test_portion]
    val_data = data[train_portion + test_portion :]

    torch.manual_seed(42)

    train_dataset = InstructionDataset(train_data, tokenizer)
    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        collate_fn=customized_collate_fn,
        shuffle=True,
        drop_last=True,
        num_workers=0,
    )
    val_dataset = InstructionDataset(val_data, tokenizer)
    val_loader = DataLoader(
        val_dataset,
        batch_size=args.batch_size,
        collate_fn=customized_collate_fn,
        shuffle=False,
        drop_last=False,
        num_workers=0,
    )

    # Load pretrained model
    variant = GPT2Variant(args.model)
    model = GPT2(MODEL_CONFIGS[variant])
    load_gpt2_weights(model, variant=variant)
    model = model.to(device)
    logger.info("Model loaded and ready for training")

    # Train
    history = train(
        model,
        train_loader,
        val_loader,
        tokenizer,
        num_epochs=args.num_epochs,
        grad_clip=1.0,
        checkpoint_interval=1,
        model_name=variant.value,
        grad_accumulation_steps=args.grad_accumulation_steps,
    )

    # Plot losses
    plot_losses(
        history["steps"], history["train_loss"], history["val_loss"], "checkpoints/sft/loss.png"
    )

    # Load best checkpoint for evaluation
    best_checkpoint_path = f"checkpoints/sft/{variant}-sft.pt"
    checkpoint = torch.load(best_checkpoint_path, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()
    logger.info(f"Loaded best checkpoint from {best_checkpoint_path}")

    # Let's take a brief look at the responses generated by the finetuned model
    for sample in test_data[:3]:
        prompt = format_input(sample)
        response_text = "\n\n### Response:\n"
        full_prompt = prompt + response_text
        generated_text = generate_and_decode(
            prompt=full_prompt,
            tokenizer=tokenizer,
            model=model,
            max_new_tokens=256,
            temperature=0.7,
            top_k=20,
            top_p=0.99,
            strategy=SamplingStrategy.STOCHASTIC,
            eos_token_id=tokenizer.eot_token,
            stream=False,
        )
        print(prompt)
        print(f"\nCorrect response:\n>> {sample['output']}")
        print(f"\nModel response:\n>> {generated_text.strip()}")
        print("-" * 50)

    # Extract all test_data responses to a json file for future evaluation
    with progress_bar("Extracting test_data responses", total=len(test_data)) as (
        progress,
        task,
    ):
        for i, sample in enumerate(test_data):
            prompt = format_input(sample)
            full_prompt = prompt + "\n\n### Response:\n"
            generated_text = generate_and_decode(
                prompt=full_prompt,
                tokenizer=tokenizer,
                model=model,
                max_new_tokens=256,
                temperature=0.5,
                top_k=20,
                top_p=0.99,
                strategy=SamplingStrategy.STOCHASTIC,
                eos_token_id=tokenizer.eot_token,
                stream=False,
            )
            test_data[i]["generated_response"] = str(generated_text).strip()
            progress.update(task, advance=1)
    with open("data/finetuning/instruction_dataset_test_responses.json", "w") as f:
        json.dump(test_data, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    main()
