codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

ignore:
  - "tests/*"

coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%
