name: tiny_shakespeare
raw_file: data/raw/tiny_shakespeare/tiny_shakespeare.txt
processed_dir: data/processed/tiny_shakespeare
tokenizer_type: bpe
vocab_size: 512
train_split: 0.9
block_size: 256
special_tokens:
  "<|endoftext|>": 100257
